name: Upgrade Python Requirements

on:
  schedule:
    # will start the job at 13:00 UTC every Friday
    - cron: "0 13 * * 5"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch against which to create requirements PR"
        required: true
        default: "main"

jobs:
  call-upgrade-python-requirements-workflow:
    uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@master
    with:
      branch: ${{ github.event.inputs.branch || '"main"' }}
      # optional parameters below; fill in if you'd like github or email notifications
      # user_reviewers: ""
      team_reviewers: "hooks-extension-framework"
      # email_address: ""
      # send_success_notification: false
    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
